#!/usr/bin/env bash

set -u
set -o pipefail

HOSTNAME=$(hostname -s)
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ ! -f "${SCRIPTS_DIR}/functions.sh" ]]; then echo "Missing ${SCRIPTS_DIR}/functions.sh file"; exit 1; fi
. "${SCRIPTS_DIR}/functions.sh"

if [[ -f "${SCRIPTS_DIR}/.env" ]]; then . "${SCRIPTS_DIR}/.env"; fi

trap exit_canary EXIT HUP INT TERM

case "$(uname -s)" in
   Darwin) OS='Mac' ;;
   Linux) OS='Linux' ;;
   *) echo 'Unsupported OS'; exit 1 ;;
esac

echo "Start on ${OS} for ${HOSTNAME}"
while true; do
  sleep 0.5s
  AWAY=0
  [[ -z ${NEW_DEVICES+x} ]] && DEVICES="" || DEVICES="${NEW_DEVICES}"

  if [[ ${OS} = 'Mac' ]]; then
    NEW_DEVICES=$(ioreg -p IOUSB -w0 | sed 's/[^o]*o //; s/@.*$//' | grep -v '^Root.*')
    # Idle for 1 minute
    IDLETIME=$(ioreg -c IOHIDSystem | awk '/HIDIdleTime/ {print int($NF/1000000000); exit}')
    [[ "${IDLETIME}" -gt "60" ]] && AWAY=1
    # No graphics capabilities
    pmset -g systemstate | grep Graphics > /dev/null || AWAY=1
    # Screensaver enabled
    pgrep -q ScreenSaverEngine > /dev/null && AWAY=1
  elif [[ ${OS} = 'Linux' ]]; then
    NEW_DEVICES=$(lsusb)
    if [[ "${DISPLAY}" != "" ]]; then
      # Idle for 1 minute
      command -v gnome-screensaver-command -q | grep -w -c inactive && AWAY=1
      command -v xprintidle && [[ "$(xprintidle)" -gt "60000" ]] && AWAY=1
      command -v xscreensaver-command && xscreensaver-command -time && AWAY=1

      if [[ "$(which qdbus)" != "" ]]; then
        # Screensaver enabled
        [[ "$(qdbus org.freedesktop.ScreenSaver /ScreenSaver org.freedesktop.ScreenSaver.GetActive)" == "true" ]] && AWAY=1
        [[ "$(qdbus org.kde.screensaver /ScreenSaver org.freedesktop.ScreenSaver.GetActive)" == "true" ]] && AWAY=1
        [[ "$(qdbus org.gnome.ScreenSaver /ScreenSaver org.gnome.ScreenSaver.GetActive)" == "true" ]] && AWAY=1
      fi
    else
      AWAY=1
    fi
  fi

  if [[ "${DEVICES}" != "" ]] && { [[ "${PARANOID}" -gt "0" ]] || [[ "${AWAY}" -gt "0" ]]; }; then
    DIFF=$(diff -U 0 <(echo "${DEVICES}") <(echo "${NEW_DEVICES}") 2>/dev/null | sed '1,3d')
    if [[ "${DIFF}" != "" ]]; then
      alert "USB CANARY on ${HOSTNAME}: ${DIFF}"
    fi
  fi

done
